# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.define "display" do |display|
    display.vm.hostname = "display"
    display.vm.network "forwarded_port", guest: 8080, host: 8080
    display.vm.network "private_network", ip: "192.168.50.20"
    display.vm.provision "shell", name: "basic_provision", inline: <<-SHELL
        apt-get update
        sudo apt install -y openjdk-11-jdk
        sudo apt install -y tomcat9
        sudo apt install -y tomcat9-admin
        sudo apt-get install -y git
        sudo groupadd tomcat9
        sudo useradd -s /bin/false -g tomcat9 -d /etc/tomcat9 tomcat9
        sudo systemctl start tomcat9
        sudo apt-get update && sudo apt-get -y install maven

        sudo cp /vagrant/tomcat-users.xml /etc/tomcat9/tomcat-users.xml
        sudo cp /vagrant/settings.xml /etc/maven/settings.xml

        mvn archetype:generate -DgroupId=org.example \
        -DartifactId=mi-aplicacion \
        -DarchetypeArtifactId=maven-archetype-webapp \
        -DinteractiveMode=false

        cp -r /vagrant/mi-aplicacion/ /mi-aplicacion

        git clone https://github.com/cameronmcnz/rock-paper-scissors.git /rock-paper-scissors
        cd /rock-paper-scissors
        git checkout patch-1
        
        cp -r /vagrant/rock-paper-scissors/ /rock-paper-scissors
      SHELL
  end #display
end

